import { nightfallCards } from "./nightfallCards";

export interface Card {
  number: number;
  name: string;
  filename: string;
  variant?: "H" | "RH"; // H = Holo, RH = Reverse Holo
}

export interface CardSet {
  id: string;
  name: string;
  shortName: string;
  cdnPath: string;
  totalCards: number;
  cards: Card[];
}

const sampleCards: Card[] = [
  { number: 1, name: "Aura Battery", filename: "Aura-Battery-Sample.png" },
  { number: 2, name: "Aura Generator", filename: "Aura-Generator-Sample.png" },
  { number: 3, name: "Aura Potion", filename: "Aura Potion Sample.png" },
  { number: 4, name: "Babe The Blue Ox", filename: "Babe-The-Blue-Ox-Sample.png" },
  { number: 5, name: "Batsquatch", filename: "Batsquatch Sample.png" },
  { number: 6, name: "Bigfoot", filename: "Bigfoot-Sample.png" },
  { number: 7, name: "Billdad", filename: "Billdad Sample.png" },
  { number: 8, name: "Black Cat", filename: "Black Cat Sample.png" },
  { number: 9, name: "Bloodlust", filename: "Bloodlust-Sample.png" },
  { number: 10, name: "Boohag", filename: "Boohag Sample.png" },
  { number: 11, name: "Book of Shadows", filename: "Book of Shadows Sample.png" },
  { number: 12, name: "Broom", filename: "Broom Sample.png" },
  { number: 13, name: "Bunny Man", filename: "Bunny Man Sample.png" },
  { number: 14, name: "Cactus Cat", filename: "Cactus Cat Sample.png" },
  { number: 15, name: "Chaos Crystal", filename: "Chaos-Crystal-Sample.png" },
  { number: 16, name: "Chupacabra", filename: "Chupacabra-Sample.png" },
  { number: 17, name: "Cosmic Aura", filename: "Cosmic Aura Sample.png" },
  {
    number: 18,
    name: "Crawfordsville Monster",
    filename: "Crawfordsville-Monster-Sample.png",
  },
  { number: 19, name: "Cumberland Dragon", filename: "Cumberland-Dragon-Sample.png" },
  { number: 20, name: "Dark Aura", filename: "Dark Aura Sample.png" },
  { number: 21, name: "Dark Crystal", filename: "Dark-Crystal-Sample.png" },
  { number: 22, name: "Death Beam", filename: "Death-Beam-Sample.png" },
  { number: 23, name: "Dingbelle", filename: "Dingbelle-Sample.png" },
  { number: 24, name: "Dover Demon", filename: "Dover-Demon-Sample.png" },
  { number: 25, name: "Dragons Breath", filename: "Dragons-Breath-Sample.png" },
  { number: 26, name: "Dual Permafrost", filename: "Dual Permafrost Sample.png" },
  { number: 27, name: "Earth Aura", filename: "Earth Aura Sample.png" },
  { number: 28, name: "Eternal Snowflake", filename: "Eternal-Snowflake-Sample.png" },
  { number: 29, name: "Exorcist's Nail", filename: "Exorcist_s Nail Sample.png" },
  { number: 30, name: "Fire Elemental", filename: "Fire-Elemental-Sample.png" },
  { number: 31, name: "Fire Trap", filename: "Fire Trap Sample.png" },
  { number: 32, name: "Fireball", filename: "Fireball Sample.png" },
  { number: 33, name: "Flame Aura", filename: "Flame Aura Sample.png" },
  { number: 34, name: "Flatwoods Monster", filename: "Flatwoods-Monster-Sample.png" },
  { number: 35, name: "Forest Aura", filename: "Forest Aura Sample.png" },
  { number: 36, name: "Forest Gods Amber", filename: "Forest-Gods-Amber-Sample.png" },
  { number: 37, name: "Fountain of Youth", filename: "Fountain-of-Youth-Sample.png" },
  {
    number: 38,
    name: "Fresno Nightcrawlers",
    filename: "Fresno-Nightcrawlers-Sample.png",
  },
  { number: 39, name: "Frost Aura", filename: "Frost Aura Sample.png" },
  {
    number: 40,
    name: "Funeral Mountain Terrashot",
    filename: "Funeral Mountain Terrashot Sample.png",
  },
  { number: 41, name: "Gee-Gee Bird", filename: "Gee-Gee Bird Sample.png" },
  { number: 42, name: "Ghost Train", filename: "Ghost-Train-Sample.png" },
  { number: 43, name: "Giant Salamander", filename: "Giant Salamander Sample.png" },
  { number: 44, name: "Giant Space Brains", filename: "Giant-Space-Brains-Sample.png" },
  { number: 45, name: "Grim Reaper", filename: "Grim-Reaper-Sample.png" },
  { number: 46, name: "Growth", filename: "Growth-Sample.png" },
  { number: 47, name: "Headless Horseman", filename: "Headless-Horseman-Sample.png" },
  { number: 48, name: "Health Potion", filename: "Health Potion Sample.png" },
  { number: 49, name: "Hodag", filename: "Hodag-Sample.png" },
  { number: 50, name: "Hopkinsville Goblin", filename: "Hopkinsville-Goblin-Sample.png" },
  { number: 51, name: "Ice Storm", filename: "Ice Storm Sample.png" },
  { number: 52, name: "Indrid Cold", filename: "Indrid-Cold-Sample.png" },
  { number: 53, name: "Jackalope", filename: "Jackalope Sample.png" },
  { number: 54, name: "Jersey Devil", filename: "Jersey-Devil-Sample.png" },
  { number: 55, name: "Johnny Appleseed", filename: "Johnny Appleseed.png" },
  { number: 56, name: "Kentucky Hellhound", filename: "Kentucky Hellhound Sample.png" },
  { number: 57, name: "Kushtaka", filename: "Kushtaka-Sample.png" },
  { number: 58, name: "Light Aura", filename: "Light Aura Sample.png" },
  { number: 59, name: "Lightning Aura", filename: "Lightning Aura Sample.png" },
  { number: 60, name: "Lightning Bolt", filename: "Lightning Bolt Sample.png" },
  { number: 61, name: "Lightning Crystal", filename: "Lightning-Crystal-Sample.png" },
  { number: 62, name: "Loveland Frogman", filename: "Loveland-Frogman-Sample.png" },
  { number: 63, name: "Matlox", filename: "Matlox Sample.png" },
  { number: 64, name: "Men in Black", filename: "Men-in-Black-Sample.png" },
  {
    number: 65,
    name: "Metal Man of Alabama",
    filename: "Metal-Man-of-Alabama-Sample.png",
  },
  { number: 66, name: "Minnesota Iceman", filename: "Minnesota Iceman Sample.png" },
  { number: 67, name: "Mothman", filename: "Mothman-Sample.png" },
  { number: 68, name: "Nain Rouge", filename: "Nain Rouge Sample.png" },
  { number: 69, name: "Napa Rebobs", filename: "Napa Rebobs Sample.png" },
  {
    number: 70,
    name: "Old Saybrook Blockheads",
    filename: "Old-Saybrook-Blockheads.png",
  },
  { number: 71, name: "Ozark Howler", filename: "Ozark Howler Sample.png" },
  { number: 72, name: "Paul Bunyan", filename: "Paul-Bunyan-Sample.png" },
  { number: 73, name: "Piasa Bird", filename: "Piasa-Bird-Sample.png" },
  { number: 74, name: "Pope Lick Monster", filename: "Pope Lick Monster Sample.png" },
  { number: 75, name: "Pukwudgie", filename: "Pukwudgie Sample.png" },
  { number: 76, name: "Quetzalcoatlus", filename: "Quetzalcoatlus-Sample.png" },
  { number: 77, name: "Razored Leaf", filename: "Razored Leaf Sample.png" },
  { number: 78, name: "River Dinos", filename: "River Dinos Sample.png" },
  { number: 79, name: "Rubberado", filename: "Rubberado Sample.png" },
  { number: 80, name: "Sam Sinclair", filename: "Sam-Sinclair-Sample.png" },
  { number: 81, name: "Sewer Alligator", filename: "Sewer Alligator Sample.png" },
  { number: 82, name: "Shock Aura", filename: "Shock Aura Sample.png" },
  { number: 83, name: "Sink Hole Sam", filename: "Sink-Hole-Sam-Sample.png" },
  { number: 84, name: "Spirit Aura", filename: "Spirit Aura Sample.png" },
  { number: 85, name: "Squonk", filename: "Squonk Sample.png" },
  { number: 86, name: "The Char Man", filename: "The Char Man Sample.png" },
  { number: 87, name: "Thorned Whip", filename: "Thorned Whip Sample.png" },
  { number: 88, name: "Tizheruk", filename: "Tizheruk-Sample.png" },
  { number: 89, name: "Tripodero", filename: "Tripodero Sample.png" },
  { number: 90, name: "Twin Meteor", filename: "Twin Meteor Sample.png" },
  { number: 91, name: "UFO", filename: "UFO-Sample.png" },
  { number: 92, name: "Van Meter Visitor", filename: "Van-Meter-Visitor-Sample.png" },
  { number: 93, name: "Walking Sam", filename: "Walking-Sam-Sample.png" },
  { number: 94, name: "Water Aura", filename: "Water Aura Sample.png" },
  { number: 95, name: "Wendigo", filename: "Wendigo-Sample.png" },
  { number: 96, name: "White Thang", filename: "White Thang Sample.png" },
];

const cryptidNationCards: Card[] = [
  { number: 1, name: "Chupacabra", filename: "1-159-Chupacabra-H.png", variant: "H" },
  { number: 1, name: "Chupacabra", filename: "1-159-Chupacabra-RH.png", variant: "RH" },
  { number: 2, name: "Jersey Devil", filename: "2-159-Jersey-Devil-H.png", variant: "H" },
  {
    number: 2,
    name: "Jersey Devil",
    filename: "2-159-Jersey-Devil-RH.png",
    variant: "RH",
  },
  { number: 3, name: "Mothman", filename: "3-159-Mothman-H.png", variant: "H" },
  { number: 3, name: "Mothman", filename: "3-159-Mothman-RH.png", variant: "RH" },
  { number: 4, name: "Bigfoot", filename: "4-159-Bigfoot-H.png", variant: "H" },
  { number: 4, name: "Bigfoot", filename: "4-159-Bigfoot-RH.png", variant: "RH" },
  { number: 5, name: "Hodag", filename: "5-159-Hodag-H.png", variant: "H" },
  { number: 5, name: "Hodag", filename: "5-159-Hodag-RH.png", variant: "RH" },
  { number: 6, name: "Lizard Man", filename: "6-159-Lizard-Man-H.png", variant: "H" },
  { number: 6, name: "Lizard Man", filename: "6-159-Lizard-Man-RH.png", variant: "RH" },
  { number: 7, name: "Snallygaster", filename: "7-159-Snallygaster-H.png", variant: "H" },
  {
    number: 7,
    name: "Snallygaster",
    filename: "7-159-Snallygaster-RH.png",
    variant: "RH",
  },
  { number: 8, name: "Uncle Sam", filename: "8-159-Uncle-Sam-H.png", variant: "H" },
  { number: 9, name: "Walking Sam", filename: "9-159-Walking-Sam-H.png", variant: "H" },
  { number: 9, name: "Walking Sam", filename: "9-159-Walking-Sam-RH.png", variant: "RH" },
  { number: 10, name: "Chessie", filename: "10-159-Chessie-H.png", variant: "H" },
  {
    number: 11,
    name: "Loveland Frogman",
    filename: "11-159-Loveland-Frogman-H.png",
    variant: "H",
  },
  {
    number: 11,
    name: "Loveland Frogman",
    filename: "11-159-Loveland-Frogman-RH.png",
    variant: "RH",
  },
  {
    number: 12,
    name: "Beast of Busco",
    filename: "12-159-Beast-of-Busco-H.png",
    variant: "H",
  },
  {
    number: 12,
    name: "Beast of Busco",
    filename: "12-159-Beast-of-Busco-RH.png",
    variant: "RH",
  },
  {
    number: 13,
    name: "Flatwoods Monster",
    filename: "13-159-Flatwoods-Monster-H.png",
    variant: "H",
  },
  {
    number: 13,
    name: "Flatwoods Monster",
    filename: "13-159-Flatwoods-Monster-RH.png",
    variant: "RH",
  },
  {
    number: 14,
    name: "Fresno Nightcrawlers",
    filename: "14-159-Fresno-Nightcrawlers-H.png",
    variant: "H",
  },
  {
    number: 14,
    name: "Fresno Nightcrawlers",
    filename: "14-159-Fresno-Nightcrawlers-RH.png",
    variant: "RH",
  },
  {
    number: 15,
    name: "Sinkhole Sam",
    filename: "15-159-SInkhole-Sam-H.png",
    variant: "H",
  },
  {
    number: 15,
    name: "Sinkhole Sam",
    filename: "15-159-SInkhole-Sam-RH.png",
    variant: "RH",
  },
  {
    number: 16,
    name: "Slide Rock Bolter",
    filename: "16-159-Slide-Rock-Bolter-H.png",
    variant: "H",
  },
  {
    number: 16,
    name: "Slide Rock Bolter",
    filename: "16-159-Slide-Rock-Bolter-RH.png",
    variant: "RH",
  },
  { number: 17, name: "Piasa Bird", filename: "17-159-Piasa-Bird-H.png", variant: "H" },
  { number: 17, name: "Piasa Bird", filename: "17-159-Piasa-Bird-RH.png", variant: "RH" },
  {
    number: 18,
    name: "Babe the Blue Ox",
    filename: "18-159-Babe-the-Blue-Ox-H.png",
    variant: "H",
  },
  {
    number: 18,
    name: "Babe the Blue Ox",
    filename: "18-159-Babe-the-Blue-Ox-RH.png",
    variant: "RH",
  },
  { number: 19, name: "Tizheruk", filename: "19-159-Tizheruk-H.png", variant: "H" },
  { number: 19, name: "Tizheruk", filename: "19-159-Tizheruk-RH.png", variant: "RH" },
  {
    number: 20,
    name: "Sam Sinclair",
    filename: "20-159-Sam-SInclair-H.png",
    variant: "H",
  },
  { number: 21, name: "Metal Man", filename: "21-159-Metal-Man-H.png", variant: "H" },
  { number: 21, name: "Metal Man", filename: "21-159-Metal-Man-RH.png", variant: "RH" },
  {
    number: 22,
    name: "Quetzalcoatlus",
    filename: "22-159-Quetzalcoatlus-H.png",
    variant: "H",
  },
  {
    number: 22,
    name: "Quetzalcoatlus",
    filename: "22-159-Quetzalcoatlus-RH.png",
    variant: "RH",
  },
  { number: 23, name: "Death Beam", filename: "23-159-Death-Beam-H.png", variant: "H" },
  { number: 24, name: "Growth", filename: "24-159-Growth-H.png", variant: "H" },
  { number: 25, name: "Powerup Red", filename: "25-159-Powerup-Red-H.png", variant: "H" },
  {
    number: 26,
    name: "Phoenix Rain",
    filename: "26-159-Phoenix-Rain-H.png",
    variant: "H",
  },
  {
    number: 27,
    name: "Silver Bullet",
    filename: "27-159-Silver-Bullet-H.png",
    variant: "H",
  },
  { number: 28, name: "Ghost Train", filename: "28-159-Ghost-Train-H.png", variant: "H" },
  { number: 29, name: "Blood Ruby", filename: "29-159-Blood-Ruby-H.png", variant: "H" },
  { number: 29, name: "Blood Ruby", filename: "29-159-Blood-Ruby-RH.png", variant: "RH" },
  {
    number: 30,
    name: "Forest God's Amber",
    filename: "30-159-Forest-Gods-Amber-H.png",
    variant: "H",
  },
  {
    number: 30,
    name: "Forest God's Amber",
    filename: "30-159-Forest-Gods-Amber-RH.png",
    variant: "RH",
  },
  {
    number: 31,
    name: "Chaos Crystal",
    filename: "31-159-Chaos-Crystal-H.png",
    variant: "H",
  },
  {
    number: 31,
    name: "Chaos Crystal",
    filename: "31-159-Chaos-Crystal-RH.png",
    variant: "RH",
  },
  {
    number: 32,
    name: "Black Hole Shard",
    filename: "32-159-Black-Hole-Shard-H.png",
    variant: "H",
  },
  {
    number: 32,
    name: "Black Hole Shard",
    filename: "32-159-Black-Hole-Shard-RH.png",
    variant: "RH",
  },
  {
    number: 33,
    name: "Earth's Core",
    filename: "33-159-Earths-Core-H.png",
    variant: "H",
  },
  {
    number: 33,
    name: "Earth's Core",
    filename: "33-159-Earths-Core-RH.png",
    variant: "RH",
  },
  {
    number: 34,
    name: "Unending Fire Crystal",
    filename: "34-159-Unending-Fire-Crystal-H.png",
    variant: "H",
  },
  {
    number: 34,
    name: "Unending Fire Crystal",
    filename: "34-159-Unending-Fire-Crystal-RH.png",
    variant: "RH",
  },
  {
    number: 35,
    name: "Eternal Snowflake",
    filename: "35-159-Eternal-Snowflake-H.png",
    variant: "H",
  },
  {
    number: 35,
    name: "Eternal Snowflake",
    filename: "35-159-Eternal-Snowflake-RH.png",
    variant: "RH",
  },
  { number: 36, name: "Holy Gem", filename: "36-159-Holy-Gem-H.png", variant: "H" },
  { number: 36, name: "Holy Gem", filename: "36-159-Holy-Gem-RH.png", variant: "RH" },
  {
    number: 37,
    name: "Lightning Glass",
    filename: "37-159-Lightning-Glass-H.png",
    variant: "H",
  },
  {
    number: 37,
    name: "Lightning Glass",
    filename: "37-159-Lightning-Glass-RH.png",
    variant: "RH",
  },
  {
    number: 38,
    name: "Medium's Third Eye",
    filename: "38-159-Mediums-Third-Eye-H.png",
    variant: "H",
  },
  {
    number: 38,
    name: "Medium's Third Eye",
    filename: "38-159-Mediums-Third-Eye-RH.png",
    variant: "RH",
  },
  {
    number: 39,
    name: "Mermaid Scales",
    filename: "39-159-Mermaid-Scales-H.png",
    variant: "H",
  },
  {
    number: 39,
    name: "Mermaid Scales",
    filename: "39-159-Mermaid-Scales-RH.png",
    variant: "RH",
  },
  { number: 40, name: "Black Cat", filename: "40-159-Black-Cat.png" },
  { number: 40, name: "Black Cat", filename: "40-159-Black-Cat-RH.png", variant: "RH" },
  { number: 41, name: "Salem's Witches", filename: "41-159-Salems-Witches.png" },
  {
    number: 41,
    name: "Salem's Witches",
    filename: "41-159-Salems-Witches-RH.png",
    variant: "RH",
  },
  { number: 42, name: "Batsquatch", filename: "42-159-Batsquatch.png" },
  { number: 42, name: "Batsquatch", filename: "42-159-Batsquatch-RH.png", variant: "RH" },
  { number: 43, name: "Bunny Man", filename: "43-159-Bunny-Man.png" },
  { number: 43, name: "Bunny Man", filename: "43-159-Bunny-Man-RH.png", variant: "RH" },
  { number: 44, name: "Chibi Mothman", filename: "44-159-Chibi-Mothman.png" },
  {
    number: 44,
    name: "Chibi Mothman",
    filename: "44-159-Chibi-Mothman-RH.png",
    variant: "RH",
  },
  { number: 45, name: "Killer Clown", filename: "45-159-Killer-Clown.png" },
  { number: 46, name: "Shadow People", filename: "46-159-Shadow-People.png" },
  { number: 47, name: "Crossroads", filename: "47-159-Crossroads.png" },
  { number: 48, name: "Gluttony", filename: "48-159-Gluttony.png" },
  { number: 49, name: "Necromancy", filename: "49-159-Necromancy.png" },
  { number: 50, name: "Book of Shadows", filename: "50-159-Book-of-Shadows.png" },
  { number: 51, name: "Broom", filename: "51-159-Broom.png" },
  {
    number: 52,
    name: "The Skeleton's Lanterns",
    filename: "52-159-The-Skeletons-Lanterns.png",
  },
  { number: 53, name: "Hide Behind", filename: "53-159-Hide-Behind.png" },
  { number: 54, name: "Hoop Snake", filename: "54-159-Hoop-Snake.png" },
  { number: 54, name: "Hoop Snake", filename: "54-159-Hoop-Snake-RH.png", variant: "RH" },
  { number: 55, name: "Squonk", filename: "55-159-Squonk.png" },
  { number: 55, name: "Squonk", filename: "55-159-Squonk-RH.png", variant: "RH" },
  { number: 56, name: "Gumberoo", filename: "56-159-Gumberoo.png" },
  { number: 57, name: "Joint Snake", filename: "57-159-Joint-Snake.png" },
  {
    number: 57,
    name: "Joint Snake",
    filename: "57-159-Joint-Snake-RH.png",
    variant: "RH",
  },
  { number: 58, name: "River Dinos", filename: "58-159-River-Dinos.png" },
  { number: 59, name: "Rumptifusel", filename: "59-159-Rumptifusel.png" },
  { number: 60, name: "Sliver Cat", filename: "60-159-Sliver-Cat.png" },
  { number: 61, name: "Wapaloosie", filename: "61-159-Wapaloosie.png" },
  { number: 62, name: "Powerup Green", filename: "62-159-Powerup-Green.png" },
  { number: 63, name: "Thorned Whip", filename: "63-159-Thorned-Whip.png" },
  { number: 64, name: "Poison Arrow", filename: "64-159-Poison-Arrow.png" },
  { number: 65, name: "Sam's 4 Leaf Clover", filename: "65-159-Sams-4-Leaf-Clover.png" },
  { number: 66, name: "White Thang", filename: "66-159-White-Thang.png" },
  { number: 67, name: "Balancing Beam", filename: "67-159-Balancing-Beam.png" },
  { number: 68, name: "Powerup Blue", filename: "68-159-Powerup-Blue.png" },
  { number: 69, name: "Scattershot", filename: "69-159-Scattershot.png" },
  { number: 70, name: "Antidote", filename: "70-159-Antidote.png" },
  { number: 71, name: "Bookmark", filename: "71-159-Bookmark.png" },
  { number: 72, name: "Catnap", filename: "72-159-Catnap.png" },
  { number: 73, name: "Pass Trap", filename: "73-159-Pass-Trap.png" },
  { number: 74, name: "Chaos Potion", filename: "74-159-Chaos-Potion.png" },
  { number: 75, name: "Luck Potion", filename: "75-159-Luck-Potion.png" },
  { number: 76, name: "Enfield Monster", filename: "76-159-Enfield-Monster.png" },
  {
    number: 76,
    name: "Enfield Monster",
    filename: "76-159-Enfield-Monster-RH.png",
    variant: "RH",
  },
  { number: 77, name: "Moon Eyed People", filename: "77-159-Moon-Eyed-People.png" },
  { number: 78, name: "Space Penguins", filename: "78-159-Space-Penguins.png" },
  {
    number: 78,
    name: "Space Penguins",
    filename: "78-159-Space-Penguins-RH.png",
    variant: "RH",
  },
  { number: 79, name: "Alien Astronaut", filename: "79-159-Alien-Astronaut.png" },
  { number: 80, name: "Proton Beam", filename: "80-159-Proton-Beam.png" },
  { number: 81, name: "Transfiguration", filename: "81-159-Transfiguration.png" },
  { number: 82, name: "Antimagic Field", filename: "82-159-Antimagic-Field.png" },
  {
    number: 83,
    name: "Funeral Mountain Terrashot",
    filename: "83-159-Funeral-Mountain-Terrashot.png",
  },
  {
    number: 83,
    name: "Funeral Mountain Terrashot",
    filename: "83-159-Funeral-Mountain-Terrashot-RH.png",
    variant: "RH",
  },
  { number: 84, name: "Cactus Cat", filename: "84-159-Cactus-Cat.png" },
  { number: 84, name: "Cactus Cat", filename: "84-159-Cactus-Cat-RH.png", variant: "RH" },
  { number: 85, name: "Matlox", filename: "85-159-Matlox.png" },
  { number: 85, name: "Matlox", filename: "85-159-Matlox-RH.png", variant: "RH" },
  { number: 86, name: "Tripodero", filename: "86-159-Tripodero.png" },
  { number: 86, name: "Tripodero", filename: "86-159-Tripodero-RH.png", variant: "RH" },
  { number: 87, name: "Rock Rain", filename: "87-159-Rock-Rain.png" },
  { number: 88, name: "Stoneskin", filename: "88-159-Stoneskin.png" },
  { number: 89, name: "Earthquake", filename: "89-159-Earthquake.png" },
  { number: 90, name: "Kentucky Hellhound", filename: "90-159-Kentucky-Hellhound.png" },
  {
    number: 90,
    name: "Kentucky Hellhound",
    filename: "90-159-Kentucky-Hellhound-RH.png",
    variant: "RH",
  },
  { number: 91, name: "Giant Salamander", filename: "91-159-Giant-Salamander.png" },
  {
    number: 91,
    name: "Giant Salamander",
    filename: "91-159-Giant-Salamander-RH.png",
    variant: "RH",
  },
  { number: 92, name: "Lava Bear", filename: "92-159-Lava-Bear.png" },
  { number: 93, name: "Dragon's Breath", filename: "93-159-Dragons-Breath.png" },
  { number: 94, name: "Fire Trap", filename: "94-159-Fire-Trap.png" },
  { number: 95, name: "Exploding Mine", filename: "95-159-Exploding-Mine.png" },
  { number: 96, name: "Fireball", filename: "96-159-Fireball.png" },
  { number: 97, name: "Gee Gee Bird", filename: "97-159-Gee-Gee-Bird.png" },
  {
    number: 97,
    name: "Gee Gee Bird",
    filename: "97-159-Gee-Gee-Bird-RH.png",
    variant: "RH",
  },
  { number: 98, name: "Snow Snake", filename: "98-159-Snow-Snake.png" },
  { number: 99, name: "Snow Wasset", filename: "99-159-Snow-Wasset.png" },
  {
    number: 99,
    name: "Snow Wasset",
    filename: "99-159-Snow-Wasset-RH.png",
    variant: "RH",
  },
  { number: 100, name: "Frozen People", filename: "100-159-Frozen-People.png" },
  { number: 101, name: "Ice Spell", filename: "101-159-Ice-Spell.png" },
  { number: 102, name: "Ice Storm", filename: "102-159-Ice-Storm.png" },
  { number: 103, name: "Icy Path", filename: "103-159-Icy-Path.png" },
  { number: 104, name: "Menehune", filename: "104-159-Menehune.png" },
  { number: 104, name: "Menehune", filename: "104-159-Menehune-RH.png", variant: "RH" },
  { number: 105, name: "Miracle Touch", filename: "105-159-Miracle-Touch.png" },
  { number: 106, name: "Retribution", filename: "106-159-Retribution.png" },
  { number: 107, name: "Light Beam", filename: "107-159-Light-Beam.png" },
  { number: 108, name: "Sam's EMF Device", filename: "108-159-Sams-EMF-Device.png" },
  { number: 109, name: "Sam's Rabbit Foot", filename: "109-159-Sams-Rabbit-Foot.png" },
  { number: 110, name: "Health Potion", filename: "110-159-Health-Potion.png" },
  { number: 111, name: "Chibi Quetza", filename: "111-159-Chibi-Quetza.png" },
  {
    number: 111,
    name: "Chibi Quetza",
    filename: "111-159-Chibi-Quetza-RH.png",
    variant: "RH",
  },
  { number: 112, name: "Grounding", filename: "112-159-Grounding.png" },
  { number: 113, name: "Haste", filename: "113-159-Haste.png" },
  { number: 114, name: "Lightning Bolt", filename: "114-159-Lightning-Bolt.png" },
  { number: 115, name: "Paralyze", filename: "115-159-Paralyze.png" },
  { number: 116, name: "Shock Aura", filename: "116-159-Shock-Aura.png" },
  {
    number: 117,
    name: "Lightning in a Bottle",
    filename: "117-159-Lightning-in-a-Bottle.png",
  },
  { number: 118, name: "Huggin Molly", filename: "118-159-Huggin-Molly.png" },
  {
    number: 118,
    name: "Huggin Molly",
    filename: "118-159-Huggin-Molly-RH.png",
    variant: "RH",
  },
  { number: 119, name: "The Spookster", filename: "119-159-The-Spookster.png" },
  { number: 120, name: "Ghost Deer", filename: "120-159-Ghost-Deer.png" },
  {
    number: 120,
    name: "Ghost Deer",
    filename: "120-159-Ghost-Deer-RH.png",
    variant: "RH",
  },
  { number: 121, name: "Old Green Eyes", filename: "121-159-Old-Green-Eyes.png" },
  { number: 122, name: "Morpheus", filename: "122-159-Morpheus.png" },
  { number: 123, name: "Pyrokinetic Blast", filename: "123-159-Pyrokinetic-Blast.png" },
  { number: 124, name: "Telekinesis", filename: "124-159-Telekinesis.png" },
  { number: 125, name: "Lake Worth Monster", filename: "125-159-Lake-Worth-Monster.png" },
  {
    number: 125,
    name: "Lake Worth Monster",
    filename: "125-159-Lake-Worth-Monster-RH.png",
    variant: "RH",
  },
  { number: 126, name: "Sewer Alligator", filename: "126-159-Sewer-Alligator.png" },
  {
    number: 126,
    name: "Sewer Alligator",
    filename: "126-159-Sewer-Alligator-RH.png",
    variant: "RH",
  },
  { number: 127, name: "Fog of War", filename: "127-159-Fog-of-War.png" },
  { number: 128, name: "Invisibility", filename: "128-159-Invisibility.png" },
  { number: 129, name: "Reflection", filename: "129-159-Reflection.png" },
  { number: 130, name: "Water Gun", filename: "130-159-Water-Gun.png" },
  { number: 131, name: "Dark Aura", filename: "131-159-Dark-Aura.png" },
  { number: 132, name: "Forest Aura", filename: "132-159-Forest-Aura.png" },
  { number: 133, name: "Cosmic Aura", filename: "133-159-Cosmic-Aura.png" },
  { number: 134, name: "Earth Aura", filename: "134-159-Earth-Aura.png" },
  { number: 135, name: "Flame Aura", filename: "135-159-Flame-Aura.png" },
  { number: 136, name: "Frost Aura", filename: "136-159-Frost-Aura.png" },
  { number: 137, name: "Light Aura", filename: "137-159-Light-Aura.png" },
  { number: 138, name: "Lightning Aura", filename: "138-159-Lightning-Aura.png" },
  { number: 139, name: "Spirit Aura", filename: "139-159-Spirit-Aura.png" },
  { number: 140, name: "Water Aura", filename: "140-159-Water-Aura.png" },
  { number: 141, name: "Meteor Shower", filename: "141-159-Meteor-Shower.png" },
  { number: 142, name: "Stars", filename: "142-159-Stars.png" },
  { number: 143, name: "Nighttime", filename: "143-159-Nighttime.png" },
  { number: 144, name: "Desert", filename: "144-159-Desert.png" },
  { number: 145, name: "Ground", filename: "145-159-Ground.png" },
  { number: 146, name: "Forest", filename: "146-159-Forest.png" },
  { number: 147, name: "Mountain", filename: "147-159-Mountain.png" },
  { number: 148, name: "Snowing", filename: "148-159-Snowing.png" },
  { number: 149, name: "Winter", filename: "149-159-Winter.png" },
  { number: 150, name: "Daytime", filename: "150-159-Daytime.png" },
  { number: 151, name: "Lightning Storm", filename: "151-159-Lightning-Storm.png" },
  { number: 152, name: "Farm", filename: "152-159-Farm.png" },
  { number: 153, name: "Suburban", filename: "153-159-Suburban.png" },
  { number: 154, name: "City", filename: "154-159-City.png" },
  { number: 155, name: "Lake", filename: "155-159-Lake.png" },
  { number: 156, name: "Ocean", filename: "156-159-Ocean.png" },
  { number: 157, name: "Raining", filename: "157-159-Raining.png" },
  { number: 158, name: "River", filename: "158-159-River.png" },
  { number: 159, name: "Island", filename: "159-159-Island.png" },
];

export const cardSets: CardSet[] = [
  {
    id: "sample",
    name: "Sample",
    shortName: "S",
    cdnPath: "https://gaichu.b-cdn.net/mz/sample",
    totalCards: 96,
    cards: sampleCards,
  },
  {
    id: "cryptid-nation",
    name: "Cryptid Nation",
    shortName: "CN",
    cdnPath: "https://gaichu.b-cdn.net/mz/cn",
    totalCards: 159,
    cards: cryptidNationCards,
  },
  {
    id: "nightfall",
    name: "Nightfall",
    shortName: "NF",
    cdnPath: "https://gaichu.b-cdn.net/mz/nf",
    totalCards: 163,
    cards: nightfallCards,
  },
];

export function getCardSet(id: string): CardSet | undefined {
  return cardSets.find((set) => set.id === id);
}

export function getCardImageUrl(set: CardSet, card: Card): string {
  return `${set.cdnPath}/${encodeURIComponent(card.filename)}`;
}
