import type { Card } from "./cardSets";

export const nightfallCards: Card[] = [
  { number: 1, name: "Grim Reaper", filename: "1-163-Grim-Reaper-NH.png" },
  { number: 1, name: "Grim Reaper", filename: "1-163-Grim-Reaper-RH.png", variant: "RH" },
  { number: 1, name: "Grim Reaper", filename: "1-163-Grim-Reaper-H.png", variant: "H" },
  { number: 2, name: "Headless Horseman", filename: "2-163-Headless-Horseman-NH.png" },
  { number: 2, name: "Headless Horseman", filename: "2-163-Headless-Horseman-RH.png", variant: "RH" },
  { number: 2, name: "Headless Horseman", filename: "2-163-Headless-Horseman-H.png", variant: "H" },
  { number: 3, name: "Indrid Cold", filename: "3-163-Indrid-Cold-NH.png" },
  { number: 3, name: "Indrid Cold", filename: "3-163-Indrid-Cold-RH.png", variant: "RH" },
  { number: 3, name: "Indrid Cold", filename: "3-163-Indrid-Cold-H.png", variant: "H" },
  { number: 4, name: "Mothman", filename: "4-163-Mothman-NH.png" },
  { number: 4, name: "Mothman", filename: "4-163-Mothman-RH.png", variant: "RH" },
  { number: 4, name: "Mothman", filename: "4-163-Mothman-H.png", variant: "H" },
  { number: 5, name: "Wendigo", filename: "5-163-Wendigo-NH.png" },
  { number: 5, name: "Wendigo", filename: "5-163-Wendigo-RH.png", variant: "RH" },
  { number: 5, name: "Wendigo", filename: "5-163-Wendigo-H.png", variant: "H" },
  { number: 6, name: "Guardian Angel", filename: "6-163-Guardian-Angel-NH.png" },
  { number: 6, name: "Guardian Angel", filename: "6-163-Guardian-Angel-RH.png", variant: "RH" },
  { number: 6, name: "Guardian Angel", filename: "6-163-Guardian-Angel-H.png", variant: "H" },
  { number: 7, name: "Adam Ackler", filename: "7-163-Adam-Ackler-NH.png" },
  { number: 7, name: "Adam Ackler", filename: "7-163-Adam-Ackler-RH.png", variant: "RH" },
  { number: 7, name: "Adam Ackler", filename: "7-163-Adam-Ackler-H.png", variant: "H" },
  { number: 8, name: "Dark Watchers", filename: "8-163-Dark-Watchers-NH.png" },
  { number: 8, name: "Dark Watchers", filename: "8-163-Dark-Watchers-RH.png", variant: "RH" },
  { number: 8, name: "Dark Watchers", filename: "8-163-Dark-Watchers-H.png", variant: "H" },
  { number: 9, name: "Frank Shaw's Gargoyle", filename: "9-163-Frank-Shaws-Gargoyle-NH.png" },
  { number: 9, name: "Frank Shaw's Gargoyle", filename: "9-163-Frank-Shaws-Gargoyle-RH.png", variant: "RH" },
  { number: 9, name: "Frank Shaw's Gargoyle", filename: "9-163-Frank-Shaws-Gargoyle-H.png", variant: "H" },
  { number: 10, name: "Grafton Monster", filename: "10-163-Grafton-Monster-NH.png" },
  { number: 10, name: "Grafton Monster", filename: "10-163-Grafton-Monster-RH.png", variant: "RH" },
  { number: 10, name: "Grafton Monster", filename: "10-163-Grafton-Monster-H.png", variant: "H" },
  { number: 11, name: "Headless Coaler", filename: "11-163-Headless-Coaler-NH.png" },
  { number: 11, name: "Headless Coaler", filename: "11-163-Headless-Coaler-H.png", variant: "H" },
  { number: 12, name: "Momo", filename: "12-163-Momo-NH.png" },
  { number: 12, name: "Momo", filename: "12-163-Momo-RH.png", variant: "RH" },
  { number: 12, name: "Momo", filename: "12-163-Momo-H.png", variant: "H" },
  { number: 13, name: "Wood Devil of Coos Country", filename: "13-163-Wood-Devil-of-Coos-Country-NH.png" },
  { number: 13, name: "Wood Devil of Coos Country", filename: "13-163-Wood-Devil-of-Coos-Country-RH.png", variant: "RH" },
  { number: 13, name: "Wood Devil of Coos Country", filename: "13-163-Wood-Devil-of-Coos-Country-H.png", variant: "H" },
  { number: 14, name: "Jack Frost", filename: "14-163-Jack-Frost-NH.png" },
  { number: 14, name: "Jack Frost", filename: "14-163-Jack-Frost-RH.png", variant: "RH" },
  { number: 14, name: "Jack Frost", filename: "14-163-Jack-Frost-H.png", variant: "H" },
  { number: 15, name: "Thunderbird", filename: "15-163-Thunderbird-NH.png" },
  { number: 15, name: "Thunderbird", filename: "15-163-Thunderbird-RH.png", variant: "RH" },
  { number: 15, name: "Thunderbird", filename: "15-163-Thunderbird-H.png", variant: "H" },
  { number: 16, name: "Bell Witch", filename: "16-163-Bell-Witch-NH.png" },
  { number: 16, name: "Bell Witch", filename: "16-163-Bell-Witch-RH.png", variant: "RH" },
  { number: 16, name: "Bell Witch", filename: "16-163-Bell-Witch-H.png", variant: "H" },
  { number: 17, name: "The Red Ghost", filename: "17-163-The-Red-Ghost-NH.png" },
  { number: 17, name: "The Red Ghost", filename: "17-163-The-Red-Ghost-RH.png", variant: "RH" },
  { number: 17, name: "The Red Ghost", filename: "17-163-The-Red-Ghost-H.png", variant: "H" },
  { number: 18, name: "Oklahoma Octopus", filename: "18-163-Oklahoma-Octopus-NH.png" },
  { number: 18, name: "Oklahoma Octopus", filename: "18-163-Oklahoma-Octopus-RH.png", variant: "RH" },
  { number: 18, name: "Oklahoma Octopus", filename: "18-163-Oklahoma-Octopus-H.png", variant: "H" },
  { number: 19, name: "Divine Covenant", filename: "19-163-Divine-Covenant-NH.png" },
  { number: 19, name: "Divine Covenant", filename: "19-163-Divine-Covenant-H.png", variant: "H" },
  { number: 20, name: "Prism Beam", filename: "20-163-Prism-Beam-NH.png" },
  { number: 20, name: "Prism Beam", filename: "20-163-Prism-Beam-H.png", variant: "H" },
  { number: 21, name: "Righteous Reckoning", filename: "21-163-Righteous-Reckoning-NH.png" },
  { number: 21, name: "Righteous Reckoning", filename: "21-163-Righteous-Reckoning-H.png", variant: "H" },
  { number: 22, name: "Borne From the Earth", filename: "22-163-Borne-From-the-Earth-NH.png" },
  { number: 22, name: "Borne From the Earth", filename: "22-163-Borne-From-The-Earth-H.png", variant: "H" },
  { number: 23, name: "Abduction", filename: "23-163-Abduction-NH.png" },
  { number: 23, name: "Abduction", filename: "23-163-Abduction-H.png", variant: "H" },
  { number: 24, name: "Boil Over", filename: "24-163-Boil-Over-NH.png" },
  { number: 24, name: "Boil Over", filename: "24-163-Boil-Over-H.png", variant: "H" },
  { number: 25, name: "Alaskan Vortex", filename: "25-163-Alaskan-Vortex-NH.png" },
  { number: 25, name: "Alaskan Vortex", filename: "25-163-Alaskan-Vortex-H.png", variant: "H" },
  { number: 26, name: "Lightning Split", filename: "26-163-Lightning-Split-NH.png" },
  { number: 27, name: "Flood the Earth", filename: "27-163-Flood-the-Earth-NH.png" },
  { number: 27, name: "Flood the Earth", filename: "27-163-Flood-the-Earth-H.png", variant: "H" },
  { number: 28, name: "River of Time", filename: "28-163-River-of-Time-NH.png" },
  { number: 28, name: "River of Time", filename: "28-163-River-of-Time-H.png", variant: "H" },
  { number: 29, name: "Potion Seller", filename: "29-163-Potion-Seller-NH.png" },
  { number: 29, name: "Potion Seller", filename: "29-163-Potion-Seller-RH.png", variant: "RH" },
  { number: 29, name: "Potion Seller", filename: "29-163-Potion-Seller-H.png", variant: "H" },
  { number: 30, name: "Stalactites", filename: "30-163-Stalactites-NH.png" },
  { number: 30, name: "Stalactites", filename: "30-163-Stalactites-H.png", variant: "H" },
  { number: 31, name: "Hell's Gate", filename: "31-163-Hells-Gate-NH.png" },
  { number: 31, name: "Hell's Gate", filename: "31-163-Hells-Gate-H.png", variant: "H" },
  { number: 32, name: "Hope Diamond", filename: "32-163-Hope-Diamond-NH.png" },
  { number: 32, name: "Hope Diamond", filename: "32-163-Hope-Diamond-RH.png", variant: "RH" },
  { number: 32, name: "Hope Diamond", filename: "32-163-Hope-Diamond-H.png", variant: "H" },
  { number: 33, name: "Obsidian Obelisk", filename: "33-163-Obsidian-Obelisk-NH.png" },
  { number: 33, name: "Obsidian Obelisk", filename: "33-163-Obsidian-Obelisk-RH.png", variant: "RH" },
  { number: 33, name: "Obsidian Obelisk", filename: "33-163-Obsidian-Obelisk-H.png", variant: "H" },
  { number: 34, name: "Twin Meteor", filename: "34-163-Twin-Meteor-NH.png" },
  { number: 34, name: "Twin Meteor", filename: "34-163-Twin-Meteor-RH.png", variant: "RH" },
  { number: 34, name: "Twin Meteor", filename: "34-163-Twin-Meteor-H.png", variant: "H" },
  { number: 35, name: "Old Book's Crying Tree", filename: "35-163-Old-Books-Crying-Tree-NH.png" },
  { number: 35, name: "Old Book's Crying Tree", filename: "35-163-Old-Books-Crying-Tree-RH.png", variant: "RH" },
  { number: 35, name: "Old Book's Crying Tree", filename: "35-163-Old-Books-Crying-Tree-H.png", variant: "H" },
  { number: 36, name: "Permafrost", filename: "36-163-Permafrost-NH.png" },
  { number: 36, name: "Permafrost", filename: "36-163-Permafrost-RH.png", variant: "RH" },
  { number: 36, name: "Permafrost", filename: "36-163-Permafrost-H.png", variant: "H" },
  { number: 37, name: "Lightning Alley", filename: "37-163-Lightning-Alley-NH.png" },
  { number: 37, name: "Lightning Alley", filename: "37-163-Lightning-Alley-RH.png", variant: "RH" },
  { number: 37, name: "Lightning Alley", filename: "37-163-Lightning-Alley-H.png", variant: "H" },
  { number: 38, name: "Boogeyman", filename: "38-163-Boogeyman-NH.png" },
  { number: 38, name: "Boogeyman", filename: "38-163-Boogeyman-RH.png", variant: "RH" },
  { number: 39, name: "Dover Demon", filename: "39-163-Dover-Demon-NH.png" },
  { number: 39, name: "Dover Demon", filename: "39-163-Dover-Demon-RH.png", variant: "RH" },
  { number: 40, name: "The Werewolf of Defiance", filename: "40-163-The-Werewolf-of-Defiance-NH.png" },
  { number: 40, name: "The Werewolf of Defiance", filename: "40-163-The-Werewolf-of-Defiance-RH.png", variant: "RH" },
  { number: 41, name: "Vampire Mercy Brown", filename: "41-163-Vampire-Mercy-Brown-NH.png" },
  { number: 42, name: "Beast of Bladenboro", filename: "42-163-Beast-of-Bladenboro-NH.png" },
  { number: 42, name: "Beast of Bladenboro", filename: "42-163-Beast-of-Bladenboro-RH.png", variant: "RH" },
  { number: 43, name: "Cabbagetown Tunnel Monster", filename: "43-163-Cabbagetown-Tunnel-Monster-NH.png" },
  { number: 44, name: "Ludwig", filename: "44-163-Ludwig-NH.png" },
  { number: 45, name: "Napa Rebobs", filename: "45-163-Napa-Rebobs-NH.png" },
  { number: 45, name: "Napa Rebobs", filename: "45-163-Napa-Rebobs-RH.png", variant: "RH" },
  { number: 46, name: "Bloodlust", filename: "46-163-Bloodlust-NH.png" },
  { number: 47, name: "Sinister Shadows", filename: "47-163-SInister-Shadows-NH.png" },
  { number: 48, name: "Zombie Apocalypse", filename: "48-163-Zombie-Apocalypse-NH.png" },
  { number: 49, name: "Nightmare", filename: "49-163-Nightmare-NH.png" },
  { number: 50, name: "Imprisonment", filename: "50-163-Imprisonment-NH.png" },
  { number: 51, name: "Smokey Spirits", filename: "51-163-Smokey-Spirits-NH.png" },
  { number: 52, name: "Headless Nun", filename: "52-163-Headless-Nun-NH.png" },
  { number: 52, name: "Headless Nun", filename: "52-163-Headless-Nun-RH.png", variant: "RH" },
  { number: 53, name: "Belled Buzzard", filename: "53-163-Belled-Buzzard-NH.png" },
  { number: 53, name: "Belled Buzzard", filename: "53-163-Belled-Buzzard-RH.png", variant: "RH" },
  { number: 54, name: "Light Elemental", filename: "54-163-Light-Elemental-NH.png" },
  { number: 54, name: "Light Elemental", filename: "54-163-Light-Elemental-RH.png", variant: "RH" },
  { number: 55, name: "Banish", filename: "55-163-Banish-NH.png" },
  { number: 56, name: "Dispel Evil", filename: "56-163-Dispel-Evil-NH.png" },
  { number: 57, name: "Holy Eyes", filename: "57-163-Holy-Eyes-NH.png" },
  { number: 58, name: "Blessed", filename: "58-163-Blessed-NH.png" },
  { number: 59, name: "Sam's Holy Water", filename: "59-163-Sams-Holy-Water-NH.png" },
  { number: 60, name: "Water to Wine", filename: "60-163-Water-to-Wine-NH.png" },
  { number: 61, name: "Crystallized Light", filename: "61-163-Crystallized-Light-NH.png" },
  { number: 62, name: "Trinity Amulet", filename: "62-163-Trinity-Amulet-NH.png" },
  { number: 63, name: "Destroy Terra", filename: "63-163-Destroy-Terra-NH.png" },
  { number: 64, name: "Feign Death", filename: "64-163-Feign-Death-NH.png" },
  { number: 65, name: "Index", filename: "65-163-Index-NH.png" },
  { number: 66, name: "Absorb Aura", filename: "66-163-Absorb-Aura-NH.png" },
  { number: 67, name: "Aura Prowess", filename: "67-163-Aura-Prowess-NH.png" },
  { number: 68, name: "Destroy Aura", filename: "68-163-Destroy-Aura-NH.png" },
  { number: 69, name: "Land Tax", filename: "69-163-Land-Tax-NH.png" },
  { number: 70, name: "Tribal Warcry", filename: "70-163-Tribal-Warcry-NH.png" },
  { number: 71, name: "Tribe Tirade", filename: "71-163-Tribe-Tirade-NH.png" },
  { number: 72, name: "Boost Aura", filename: "72-163-Boost-Aura-NH.png" },
  { number: 73, name: "Caster Center MD", filename: "73-163-Caster-Center-MD-NH.png" },
  { number: 74, name: "The Purple Blob of Philadelphia", filename: "74-163-The-Purple-Blob-of-Philadelphia-NH.png" },
  { number: 74, name: "The Purple Blob of Philadelphia", filename: "74-163-The-Purple-Blob-of-Philadelphia-RH.png", variant: "RH" },
  { number: 75, name: "Veggieman", filename: "75-163-Veggieman-NH.png" },
  { number: 75, name: "Veggieman", filename: "75-163-Veggieman-RH.png", variant: "RH" },
  { number: 76, name: "Air Rods", filename: "76-163-Air-Rods-NH.png" },
  { number: 76, name: "Air Rods", filename: "76-163-Air-Rods-RH.png", variant: "RH" },
  { number: 77, name: "Crazy Critter of Bald Mountain", filename: "77-163-Crazy-Critter-of-Bald-Mountain-NH.png" },
  { number: 77, name: "Crazy Critter of Bald Mountain", filename: "77-163-Crazy-Critter-of-Bald-Mountain-RH.png", variant: "RH" },
  { number: 78, name: "Kinderhook Blob", filename: "78-163-Kinderhook-Blob-NH.png" },
  { number: 78, name: "Kinderhook Blob", filename: "78-163-Kinderhook-Blob-RH.png", variant: "RH" },
  { number: 79, name: "Cosmic Warp", filename: "79-163-Cosmic-Warp-NH.png" },
  { number: 80, name: "Brain in a Jar", filename: "80-163-Brain-in-a-Jar-NH.png" },
  { number: 81, name: "Murphysboro Mud Monster", filename: "81-163-Murphysboro-Mud-Monster-NH.png" },
  { number: 81, name: "Murphysboro Mud Monster", filename: "81-163-Murphysboro-Mud-Monster-RH.png", variant: "RH" },
  { number: 82, name: "Teihiihan", filename: "82-163-Teihiihan-NH.png" },
  { number: 82, name: "Teihiihan", filename: "82-163-Teihiihan-RH.png", variant: "RH" },
  { number: 83, name: "Tuttle Bottoms Monster", filename: "83-163-Tuttle-Bottoms-Monster-NH.png" },
  { number: 83, name: "Tuttle Bottoms Monster", filename: "83-163-Tuttle-Bottoms-Monster-RH.png", variant: "RH" },
  { number: 84, name: "Wunk", filename: "84-163-Wunk-NH.png" },
  { number: 84, name: "Wunk", filename: "84-163-Wunk-RH.png", variant: "RH" },
  { number: 85, name: "Earth's Binding", filename: "85-163-Earths-Binding-NH.png" },
  { number: 86, name: "Excavation", filename: "86-163-Excavation-NH.png" },
  { number: 87, name: "Graveyard's Mud", filename: "87-163-Graveyards-Mud-NH.png" },
  { number: 88, name: "Feu Follet", filename: "88-163-Feu-Follet-NH.png" },
  { number: 88, name: "Feu Follet", filename: "88-163-Feu-Follet-RH.png", variant: "RH" },
  { number: 89, name: "Teakettler", filename: "89-163-Teakettler-NH.png" },
  { number: 89, name: "Teakettler", filename: "89-163-Teakettler-RH.png", variant: "RH" },
  { number: 90, name: "Jack o Lantern Bomb", filename: "90-163-Jack-o-Lantern-Bomb-NH.png" },
  { number: 91, name: "Unholy Fire", filename: "91-163-Unholy-Fire-NH.png" },
  { number: 92, name: "Pyre", filename: "92-163-Pyre-NH.png" },
  { number: 93, name: "Smokescreen", filename: "93-163-Smokescreen-NH.png" },
  { number: 94, name: "Bubbling Brew", filename: "94-163-Bubbling-Brew-NH.png" },
  { number: 95, name: "Arkansas Snipe", filename: "95-163-Arkansas-Snipe-NH.png" },
  { number: 95, name: "Arkansas Snipe", filename: "95-163-Arkansas-Snipe-RH.png", variant: "RH" },
  { number: 96, name: "Axehandle Hound", filename: "96-163-Axehandle-Hound-NH.png" },
  { number: 96, name: "Axehandle Hound", filename: "96-163-Axehandle-Hound-RH.png", variant: "RH" },
  { number: 97, name: "Lufferlang", filename: "97-163-Lufferlang-NH.png" },
  { number: 97, name: "Lufferlang", filename: "97-163-Lufferlang-RH.png", variant: "RH" },
  { number: 98, name: "Bursting Spiderlings", filename: "98-163-Bursting-Spiderlings-NH.png" },
  { number: 99, name: "Jack o Lantern", filename: "99-163-Jack-o-Lantern-NH.png" },
  { number: 100, name: "Nightshade", filename: "100-163-Nightshade-NH.png" },
  { number: 101, name: "Exquisite Stew", filename: "101-163-Exquisite-Stew-NH.png" },
  { number: 102, name: "Qalupalik", filename: "102-163-Qalupalik-NH.png" },
  { number: 102, name: "Qalupalik", filename: "102-163-Qalupalik-RH.png", variant: "RH" },
  { number: 103, name: "A Mi Kuk", filename: "103-163-A-Mi-Kuk-NH.png" },
  { number: 103, name: "A Mi Kuk", filename: "103-163-A-Mi-Kuk-RH.png", variant: "RH" },
  { number: 104, name: "Iliamna Lake Monster", filename: "104-163-Iliamna-Lake-Monster-NH.png" },
  { number: 105, name: "Great Blizzard", filename: "105-163-Great-Blizzard-NH.png" },
  { number: 106, name: "Frostbite", filename: "106-163-Frostbite-NH.png" },
  { number: 107, name: "Iceberg", filename: "107-163-Iceberg-NH.png" },
  { number: 108, name: "Copy Cup", filename: "108-163-Copy-Cup-NH.png" },
  { number: 109, name: "Poltergeist", filename: "109-163-Poltergeist-NH.png" },
  { number: 109, name: "Poltergeist", filename: "109-163-Poltergeist-RH.png", variant: "RH" },
  { number: 110, name: "The Columbia River Sand Squink", filename: "110-163-The-Columbia-River-Sand-Squink-NH.png" },
  { number: 110, name: "The Columbia River Sand Squink", filename: "110-163-The-Columbia-River-Sand-Squink-RH.png", variant: "RH" },
  { number: 111, name: "Simultaneous Bioluminescence", filename: "111-163-Simultaneous-Bioluminescence-NH.png" },
  { number: 112, name: "Witch's Lightning", filename: "112-163-Witchs-Lightning-NH.png" },
  { number: 113, name: "Static Wand", filename: "113-163-Static-Wand-NH.png" },
  { number: 114, name: "Spooky Kite", filename: "114-163-Spooky-Kite-NH.png" },
  { number: 115, name: "Dark Lightning Orb", filename: "115-163-Dark-Lightning-Orb-NH.png" },
  { number: 116, name: "Specter Moose", filename: "116-163-Specter-Moose-NH.png" },
  { number: 116, name: "Specter Moose", filename: "116-163-Specter-Moose-RH.png", variant: "RH" },
  { number: 117, name: "Black Eyed Children", filename: "117-163-Black-Eyed-Children-NH.png" },
  { number: 118, name: "Familiar", filename: "118-163-Familiar-NH.png" },
  { number: 119, name: "Robert the Doll", filename: "119-163-Robert-the-Doll-NH.png" },
  { number: 120, name: "Halloween Ghost Sheet", filename: "120-163-Halloween-Ghost-Sheet-NH.png" },
  { number: 121, name: "Possession", filename: "121-163-Possession-NH.png" },
  { number: 122, name: "Unlucky Potion", filename: "122-163-Unlucky-Potion-NH.png" },
  { number: 123, name: "Bloody Bones", filename: "123-163-Bloody-Bones-NH.png" },
  { number: 124, name: "The Bandage Man of Cannon Beach", filename: "124-163-The-Bandage-Man-of-Cannon-Beach-NH.png" },
  { number: 124, name: "The Bandage Man of Cannon Beach", filename: "124-163-The-Bandage-Man-of-Cannon-Beach-RH.png", variant: "RH" },
  { number: 125, name: "Wallowa Lake Crustacean", filename: "125-163-Wallowa-Lake-Crustacean-NH.png" },
  { number: 125, name: "Wallowa Lake Crustacean", filename: "125-163-Wallowa-Lake-Crustacean-RH.png", variant: "RH" },
  { number: 126, name: "Water Baby of Massacre Rock", filename: "126-163-Water-Baby-of-Massacre-Rock-NH.png" },
  { number: 127, name: "Dampen", filename: "127-163-Dampen-NH.png" },
  { number: 128, name: "Torrential River", filename: "128-163-Torrential-River-NH.png" },
  { number: 129, name: "Mermaid's Shimmer", filename: "129-163-Mermaids-Shimmer-NH.png" },
  { number: 130, name: "Dark Aura", filename: "130-163-Dark-Aura-NH.png" },
  { number: 131, name: "Light Aura", filename: "131-163-Light-Aura-NH.png" },
  { number: 132, name: "Cosmic Aura", filename: "132-163-Cosmic-Aura-NH.png" },
  { number: 133, name: "Earth Aura", filename: "133-163-Earth-Aura-NH.png" },
  { number: 134, name: "Flame Aura", filename: "134-163-Flame-Aura-NH.png" },
  { number: 135, name: "Forest Aura", filename: "135-163-Forest-Aura-NH.png" },
  { number: 136, name: "Frost Aura", filename: "136-163-Frost-Aura-NH.png" },
  { number: 137, name: "Lightning Aura", filename: "137-163-Lightning-Aura-NH.png" },
  { number: 138, name: "Spirit Aura", filename: "138-163-Spirit-Aura-NH.png" },
  { number: 139, name: "Water Aura", filename: "139-163-Water-Aura-NH.png" },
  { number: 140, name: "Meteor Shower", filename: "140-163-Meteor-Shower-NH.png" },
  { number: 141, name: "Stars", filename: "141-163-Stars-NH.png" },
  { number: 142, name: "Nightime", filename: "142-163-Nightime-NH.png" },
  { number: 143, name: "Full Moon", filename: "143-163-Full-Moon-NH.png" },
  { number: 144, name: "Desert", filename: "144-163-Desert-NH.png" },
  { number: 145, name: "Ground", filename: "145-163-Ground-NH.png" },
  { number: 146, name: "Swamp", filename: "146-163-Swamp.png" },
  { number: 147, name: "Forest", filename: "147-163-Forest-NH.png" },
  { number: 148, name: "Mountain", filename: "148-163-Mountain-NH.png" },
  { number: 149, name: "Snowing", filename: "149-163-Snowing-NH.png" },
  { number: 150, name: "Winter", filename: "150-163-Winter-NH.png" },
  { number: 151, name: "Dawn", filename: "151-163-Dawn-NH.png" },
  { number: 152, name: "Daytime", filename: "152-163-Daytime-NH.png" },
  { number: 153, name: "Dusk", filename: "153-163-Dusk-NH.png" },
  { number: 154, name: "Lightning Storm", filename: "154-163-Lightning-Storm-NH.png" },
  { number: 155, name: "Farm", filename: "155-163-Farm-NH.png" },
  { number: 156, name: "Suburban", filename: "156-163-Suburban-NH.png" },
  { number: 157, name: "City", filename: "157-163-City-NH.png" },
  { number: 158, name: "Fog", filename: "158-163-Fog-NH.png" },
  { number: 159, name: "Lake", filename: "159-163-Lake-NH.png" },
  { number: 160, name: "Ocean", filename: "160-163-Ocean-NH.png" },
  { number: 161, name: "Raining", filename: "161-163-Raining-NH.png" },
  { number: 162, name: "River", filename: "162-163-River-NH.png" },
  { number: 163, name: "Island", filename: "163-163-Island-NH.png" },
];

